### PR TITLE
Support for ES5 without having to deploy a transpiled version + updated ajv

### PR DESCRIPTION
**Pull request by Vadorequest**
Here is an example of what I did to use this lib with react-create-app, basically avoid special ES6 stuff because there is no transpilation (build directory)

### CODE REVIEW

**Comment by Vadorequest** [comment]
Note that I used my own version, but maybe it should be released as 1.0.3 for you instead

**Comment by DivineGod** [comment]
Can you take a look at https://github.com/DivineGod/ajv-error-messages/pull/6 and see if that helps you out?

**Comment by Vadorequest** [comment]
Thanks, I'd need to go back to the project to see how it works out, could work, not sure, was 6 months ago.

**Comment by DivineGod** [comment]
Yeah, sorry about the delay, finally caught up on 3000 github notifications :)

**Comment by Vadorequest** [comment]
What should be done about this? 

---
>Can you take a look at #6 and see if that helps you out?


I don't know what parcel is, nor how it would help, seems to be some build utility? If it's a way to generate some ES5 valid code then yes, it may help.

**Pull request closed without merging**
